server {
    listen 80;

    server_name localhost;

    location / {
        # Forward traffic to the service name 'java_app' on Spring's port 8080
        proxy_pass http://java_app:8080;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
